# -*- coding: utf-8 -*-
"""scrapeNSW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j6GWtx8zgAmwML6vkUdTj1qrI8VMTOjp
"""

import numpy as np
import pandas as pd
from datetime import date


# Load csv archive data from github repo
path='https://raw.githubusercontent.com/dgcarr/COVIDnswStatus/master/NSW_HealthData.csv'
df=pd.read_csv(path, index_col=0)
df['Date'] = pd.to_datetime(df['Date'],dayfirst=True)

today = date.today()
# dd/mm/YY
currentdate = today.strftime("%d/%m/%Y")
#print('Current date is:', currentdate)

#dfall = pd.read_html('https://www.health.nsw.gov.au/Infectious/diseases/Pages/covid-19-latest.aspx', flavor='html5lib')
#dfall

dforigins = pd.read_html('https://www.health.nsw.gov.au/Infectious/diseases/Pages/covid-19-latest.aspx',match='Source',header=0)
dforigins=dforigins[0]

dforigins['Source'] = dforigins['Source'].str.replace('\d+', '')


if dforigins['Cases'].dtypes =='object':
  #print(dforigins['Cases'].dtypes)
  dforigins['Cases'] = dforigins['Cases'].str.replace(u'\u200b', '')
  dforigins['Cases'] = dforigins['Cases'].str.replace(',', '')
  dforigins['Cases'] = dforigins['Cases'].apply(pd.to_numeric)


nc=dforigins.loc[dforigins['Source'] == 'Total','Cases'].values[0]
#nc=nc[0]
print(nc)

ui = dforigins.loc[dforigins['Source'] == 'Under investigation','Cases'].values[0]
print(ui)

un = dforigins.loc[dforigins['Source'] == 'Locally acquired – contact not identified','Cases'].values[0]
print(un)

ui_un=ui+un
print(ui_un)
#dforigins

dfnew = pd.read_html('https://www.health.nsw.gov.au/Infectious/diseases/Pages/covid-19-latest.aspx',match='Cases',header=0)
dfnew=dfnew[0]

dfnew['Cases'] = dfnew['Cases'].str.replace('\d*', '')

if dforigins['Cases'].dtypes =='object':
  dfnew['Count'] = dfnew['Count'].str.replace(u'\u200b', '')
  dfnew['Count'] = dfnew['Count'].str.replace(',', '')
  dfnew['Count'] = dfnew['Count'].apply(pd.to_numeric)

#tc=dfnew.loc[dfnew['Cases'] == 'Cases tested and excluded','Count'].values
#tc=dfnew.loc[dfnew['Cases'] == 'Cases tested and excluded','Count'].values[0]
tc=dfnew['Count'][-2:-1].values[0]
#print(tc)

deaths=dfnew.loc[dfnew['Cases'] == 'Total deaths','Count'].values[0]
#print(deaths)
#dfnew

# dfstatus = pd.read_html('https://www.health.nsw.gov.au/Infectious/diseases/Pages/covid-19-latest.aspx',match='Status',header=0)
# dfstatus=dfstatus[0]
# if dfstatus['Cases'].dtypes =='object':
#   dfstatus['Cases'] = dfstatus['Cases'].str.replace(u'\u200b', '')
#   dfstatus['Cases'] = dfstatus['Cases'].str.replace(',', '')
#   dfstatus['Cases'] = dfstatus['Cases'].apply(pd.to_numeric)
# #print(dfstatus)
# deaths=dfstatus.loc[dfstatus['Status'] == 'Total deaths','Cases'].values[0]
# #print(deaths)
# #dfstatus

df_update=pd.DataFrame({'Date':[currentdate] ,
                    'Confirmed Cases':[nc],
                    'Tested and Cleared':[tc],
                    'Unexplained Origin':[ui_un],
                    'Deaths':[deaths]}, 
                    columns = ['Date','Confirmed Cases','Tested and Cleared','Unexplained Origin','Deaths'])
df_update['Date'] = pd.to_datetime(df_update['Date'],dayfirst=True)
dfapp=df.append(df_update,ignore_index=True,)
print(dfapp)
if dfapp['Date'].iloc[-1]>df['Date'].iloc[-1]:
         df=dfapp

df.to_csv("NSW_HealthData.csv")
df